### ISSUE TITLE
What's causing the merge?

### ISSUE THREAD

**Issue by hkmshb** [ssjnr/fourkilled#4]
I've noticed that each time you push to GitHub afterwards you merge. What is the reason for this? It's unusually to merge the way you've been doing, I suppose you are doing something wrong somewhere. So comment on this Issues and provide the steps you've been using to push your codes, I'd go through and point out what to do and not do to prevent this from happening.

**Comment by Shaibujnr** [comment]
Glad you asked. i also noticed it, was planning to ask. After i commit my works in git i try to push from the gui and also (git push origin master) from bash...after filling in the necessary username and password in both interface, it brings up an error suggesting i pull first then trying the push command again so i run the command (git pull origin master) from bash then i do the push command and it works.No Error...this happened the two times i commit my work to github. so i guess it's from the git pull i usually do.
    Although i remember after seeing the suggestion, i  tried to pull from the gui but there was no pull option so i fetched and merged. This was the first time when i uploaded the code I can't remember if i  did it the second time too.

**Comment by Shaibujnr** [comment]
i just made my third commit and there was no merge, i did the push directly and it worked.
